name: Mac OS Build
on:
  push:
  workflow_dispatch:

env:
  CARGO_TERM_COLOR: always
  
jobs:
  build:
    name: Mac OS Build
    permissions: write-all
    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v4
    
    - name: Install dependencies
      run: |
        brew install ffmpeg pkg-config

    - name: Build
      run: cargo build --release --verbose

    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        path: target/release/discordify
